### ISSUE TITLE
Retrieve a thread by the main link instead of the last link

### ISSUE THREAD

**Issue by fuhadabdulla** [kbravh/obsidian-tweet-to-markdown#1]
The plugin is just awesome 
But it would be great if we just copy the link of the thread instead of the link of the last tweet in the thread.

Otherwise great work

**Comment by kbravh** [comment]
Hi @skillhacker-code! I agree, it would be much more convenient. Unfortunately, this is a limitation of the current Twitter v2 API. [Searching by thread/conversation ID](https://developer.twitter.com/en/docs/twitter-api/conversation-id) is only available on the recent search endpoint (only has tweets from the last 7 days) or the academic search endpoint (which is expensive and limited to university researchers).

The current workaround of using the last tweet and working back up the thread will work for any tweet even if it's not recent and allows anyone with a free bearer token to capture threads. 

Hope that helps explain the reasoning behind the behavior!

**Comment by fuhadabdulla** [comment]
Thank you so much for answering and developing this awesome plugin . i have been searching for a way to save twitter thread for a long time and tried many solutions like https://threadreaderapp.com/ and it was cumbersome but yours plugin is awesome .
