### ISSUE TITLE
"Note Location" does not allow nested directories (strips path characters)

### ISSUE THREAD

**Issue by clintgibler** [kbravh/obsidian-tweet-to-markdown#12]
First off, thanks for creating an awesome plugin, it saves me a ton of time! 🙏 

I'm trying to set the "Note Location" to a nested directory, for example, `assets/twitter`.

![Screen Shot 2022-04-10 at 5 10 08 PM](https://user-images.githubusercontent.com/767449/162646030-a75cf284-2e28-4ede-8cf8-fc1cf1b9491a.png)

However, when I download a tweet, it deletes the `/` and merges the path:

![Screen Shot 2022-04-10 at 5 10 49 PM](https://user-images.githubusercontent.com/767449/162646065-edcba33d-7daf-4e30-aeb8-0a566f79611e.png)

Ideally I would like to be able to save tweets to arbitrary folders, not just top level ones.

Thanks again so much for creating a great plugin!

**Comment by kbravh** [comment]
Hi @clintgibler! I'm glad you like the plugin, and thanks for catching this bug. I must have broken this while I was working on a path sanitization thing. Let me see what I can do!

**Comment by clintgibler** [comment]
Hey! Thanks for the quick response @kbravh! If it'd be useful, I'd be happy to mention a handful of small things that would be nice from a UX point of view as well, but I don't want to annoy you 😄  

Also, do you have a Buy Me a Coffee or GitHub Sponsor thingy? No pressure, it's just nice to give back to open source that I use :)

**Comment by kbravh** [comment]
I would absolutely love any and all feedback! Feel free to drop it here. 

I have a Kofi! :point_right: https://ko-fi.com/kbravh

**Comment by kbravh** [comment]
I've just released version 2.3.2 that fixes this issue. I've also begun adding tests to hopefully prevent silly stuff like this in the future. Hope this helps!

**Comment by clintgibler** [comment]
It works, thanks so much! 🙌  Will create a few standalone issues so things don't get cluttered in this issue.
