### ISSUE TITLE
Add setting to "open newly created file automatically"

### ISSUE THREAD

**Issue by clintgibler** [kbravh/obsidian-tweet-to-markdown#13]
When I import a tweet, often I want to immediately go to that file so I can add some tags, link to other notes, etc.

Currently, I have to manually navigate to the newly created file for the tweet (or tweet thread), which is not too much work, but it'd be nice to have Obsidian automatically open the new file on creation.

Maybe it's a setting you can select true/false to always default to that behavior, maybe it's (also) an option on the "Download Tweet" popup dialog box, not sure what is the best UX. Curious to what you think, or if you would find this useful.

This would be convenient, but is not necessarily a big issue in my opinion, maybe like P2 🤷

**Comment by kbravh** [comment]
Honestly this is a pain point that I always wish I'd fix every time I download a tweet too :sweat_smile: I think I'll add a setting "Open tweet once downloaded" with the options
- New tab
- Same window
- Never

**Comment by clintgibler** [comment]
Haha nice, OK it's not just me :) That setting sounds great, and good thinking re: those options, I like it :D 👍

**Comment by kbravh** [comment]
I've just released version 2.4.0 with the option as described above. I've tested it a bit and it is much more convenient now :slightly_smiling_face:

**Comment by clintgibler** [comment]
Woo so seamless, love it! Definitely more convenient for my workflow too :) Thanks so much for your responsiveness! 🙏
