### ISSUE TITLE
Autocomplete for file paths in Settings

### ISSUE THREAD

**Issue by clintgibler** [kbravh/obsidian-tweet-to-markdown#15]
For the "Note Location" and "Image Location" settings in Tweet to Markdown's settings page, it would be nice if instead of a freeform text box it was an autocomplete selector for directories in your vault.

This would both be easier for the user to select the folder they intend, and prevent them from spelling errors or other mistakes that could cause Tweet to Markdown to save tweets in a location the user wasn't intending.

The [Templater plugin](https://github.com/SilentVoid13/Templater) does this, I wonder if it has some code or an approach that would be easy to borrow?

**Comment by kbravh** [comment]
Thanks a ton for the reference plugin, that's going to make this so much easier to 
implement. I agree that this would be a great feature.

**Comment by kbravh** [comment]
Version 2.4.1 is now out and has this feature! Again, huge thanks for the Templater plugin reference and the suggestion.

**Comment by clintgibler** [comment]
o0o Awesome thanks, this is great! :D
