### ISSUE TITLE
Provide tweet text for titles

### ISSUE THREAD

**Issue by fuhadabdulla** [kbravh/obsidian-tweet-to-markdown#2]
Hi thank you developing this amazing plugin i have a small request .

Can you please grab the first tweet in a twitter thread and then make that the title of the file that twitter thread is saved in

**Comment by kbravh** [comment]
Hey there! Glad you're enjoying the plugin and providing feedback. What I can do is provide a `[[text]]` placeholder that you can use when naming the file. For threads, this will be the text of the first tweet. I should have this pushed out today.
