### ISSUE TITLE
[bug] profile pictures aren't updated if they were saved before

### ISSUE THREAD

**Issue by brain-empty** [kbravh/obsidian-tweet-to-markdown#24]
to be clear; i'm talking about making a new import and this new import has the same pfp as the users pfp from previous notes. so like even if the tweet was made today and the download itself was done today, the users pfp will remain the same as whatever the previous note was using for that users profile picture

maybe i've done something wrong but i haven't really changed much so i don't think this is a problem on my side? as far as i can tell it's probably just that the images are saved under the same name so it just uses the old reference instead of download a new one

i should also mention, i'm not talking about the previous pages being updated with the new profile picture but i think the newer downloads should have the newer pfp that the user has at the time of download right?

**Comment by kbravh** [comment]
That's a really good point, thanks for catching that! Let me look into this and see what I can do. I definitely agree that new posts should have the corresponding profile pictures.

**Comment by kbravh** [comment]
Hey @brain-empty, I've just released version 2.7.1 of the plugin that fixes this bug. Thanks again for catching it!
