### ISSUE TITLE
[feature request] Fetched timestamp

### ISSUE THREAD

**Issue by levifig** [kbravh/obsidian-tweet-to-markdown#26]
Hey 👋 

It'd be neat to have extra an Frontmatter tag: "fetched", with the timestamp of when the tweet was… well… _fetched_. 😅 

Thank you for your work!

**Comment by kbravh** [comment]
Good call, that's a useful bit of information. I'll look for the best way to add it.

**Comment by kbravh** [comment]
@levifig Version 2.8.0 is being published now, which will include a `fetched` line in the frontmatter. It will match the formatting of the timestamp set in your Tweet to Markdown settings page (one of the very last settings).

**Comment by levifig** [comment]
Awesome! Thank you! 💪 🙏
