### ISSUE TITLE
[feature request] Avatar/image size

### ISSUE THREAD

**Issue by levifig** [kbravh/obsidian-tweet-to-markdown#27]
Hey 👋 

Obsidian/Markdown allows you to specific an image size by including at least an X/Y value (or both) in the image link tag: `![avatar|50](avatar_normal.jpg)`.

It'd be cool to be able to specify those values as an option, probably a size for the avatars, and another size for "other images".

Thank your for your awesome work.
--LF

**Comment by kbravh** [comment]
@levifig That's a wonderful suggestion! I've added a task for it, so I'll take care of it soon. Thanks!

**Comment by kbravh** [comment]
Version 2.9.0 is going out right now. You'll find two new options under the settings for adjusting image size and profile image size! Thanks again for the suggestion.

**Comment by levifig** [comment]
Fantastic! Thank you for your work and the quick turnaround! 💪 🙏

**Comment by levifig** [comment]
FWIW, #29 closes this.
