### ISSUE TITLE
[[text]] placeholder can have illegal characters

### ISSUE THREAD

**Issue by fuhadabdulla** [kbravh/obsidian-tweet-to-markdown#3]
Thank you so much for taking into account my suggesion on text place holder .

Can you please remove illegal character from the first tweet before parsing it as a title .

Characters like

![WGn8Xcb0tK](https://user-images.githubusercontent.com/68536959/141041713-d913f9fe-37d2-4623-8b5d-53f6595e2cc4.png)

**Comment by kbravh** [comment]
Thanks for catching that! I used a method that Obsidian provides for cleaning up filenames, but it looks like it doesn't catch everything. I'll go ahead and implement another.

**Comment by kbravh** [comment]
Version 1.1.1 has just been published which will alleviate this issue. Thanks for reaching out!

**Comment by fuhadabdulla** [comment]
Thank you so much for fixing this
