### ISSUE TITLE
[feature request] Option to always have Twee Thread Enabled

### ISSUE THREAD

**Issue by tracure1337** [kbravh/obsidian-tweet-to-markdown#34]
[feature request] Option to always have Twee Thread Enabled

I only always download threads so for me it would be great to be able to have an option to automatically have "Downloads as Thread enabled".
(Option in the settings menu)

Icing on the cake would be an additional option to have no new document created with the thread but instead have it just copied to clipboard on saving.
(Option for the main window).

Cheers & Thanks for consideration!

**Comment by kbravh** [comment]
@cocoonkid I've just published version 2.11.0, which now includes a new setting **Default to thread download**. I'll create a separate issue for the clipboard feature!
