### ISSUE TITLE
parsing line-breaks in image ALT tag description

### ISSUE THREAD

**Issue by gapmiss** [kbravh/obsidian-tweet-to-markdown#35]
Ran across a tweet that TTM could not parse correctly due to an empty line-break.

https://twitter.com/ATechAjay/status/1560988072262520833

![1560988072262520833-a](https://user-images.githubusercontent.com/98914514/189518117-e203b9c2-4240-482e-8515-d3d220d96e5d.png)

![1560988072262520833-b](https://user-images.githubusercontent.com/98914514/189518118-d4bc9194-5a7e-4a6e-8695-28c5795187c9.png)

**Comment by kbravh** [comment]
Hi @gapmiss, thanks for catching this one. I fixed this in https://github.com/kbravh/tweet-to-markdown/commit/a688b44d3fc1cd8a766014e09db6e0cb44825847 and forgot to apply the bug fix here. This is now fixed in version 2.10.5
