### ISSUE TITLE
Make a tweet to markdown browser extension

### ISSUE THREAD

**Issue by fuhadabdulla** [kbravh/obsidian-tweet-to-markdown#4]
It would be great if you can make this plugin a browser extension .

Only if you think that it is worth your effort . 

I think there is a huge gap for thread saver browser extension 

but to tell the truth when I searched for tweet saver extension , the  existing tweet thread saver only have very less downloads. 

But there are website like threadunroller , readwise etc 

I still think there is a gap . Only if you think it is worth your effort .

**Comment by kbravh** [comment]
I agree that there's definitely an opportunity to apply the techniques in this plugin and my [tweet to markdown CLI](https://github.com/kbravh/obsidian-tweet-to-markdown) to a browser extension. Unfortunately, I don't have the bandwidth to tackle that project.

Both of my projects are completely open source, though, so if anyone would like to use what I've written to make a browser extension, they'd be more than welcome to do so.
