### ISSUE TITLE
[feature request] Escaping hashtags in Tweets

### ISSUE THREAD

**Issue by jcblsn** [kbravh/obsidian-tweet-to-markdown#42]
I wonder if it would be possible to add a toggle that, on downloading a tweet, escaped all of the hashtags in the tweet (`\#` for `#`) so as to not add clutter to the user's Obsidian tags?

**Comment by kbravh** [comment]
@eliason-j Great suggestion; I don't use tags often, but you're right that it would easily pollute the Obsidian tags. Please check out version 2.12.0! There's a new **Escape hashtags** settings :)

**Comment by jcblsn** [comment]
Oh my bad for not checking that first! Thanks so much!
