### ISSUE TITLE
Usage limit has been met 

### ISSUE THREAD

**Issue by AlaaYasser0210** [kbravh/obsidian-tweet-to-markdown#46]
Hi,
Thanks for the amazing plugin
was using smoothly till now. It says: Usage limit has been met 200/200
What is that? And will I be able to use it again?

**Comment by kbravh** [comment]
Hi @AlaaYasser0210! Glad you're liking the plugin. 
For the free API key from the TTM website, there are 200 free tweets you can download each month. You can see when it resets on your account page: https://ttm.kbravh.dev/account.

You can switch to a paid plan at https://ttm.kbravh.dev/pricing, which lets you pay per tweet to download more than 200/mo, or you can apply for a Twitter developer token, which is free and has no limit (see the instructions in the readme here: https://github.com/kbravh/obsidian-tweet-to-markdown#twitter-developer-bearer-token).

Hope that helps!

**Comment by AlaaYasser0210** [comment]
Thank you so much
I applied for Twitter API using your instructions
