### ISSUE TITLE
Mobile functionality is broken

### ISSUE THREAD

**Issue by kbravh** [kbravh/obsidian-tweet-to-markdown#5]
The plugin does not load anymore on version 1.1.2. This is _probably_ due to the filename sanitization package.

**Comment by fuhadabdulla** [comment]
I am also facing the same issue

**Comment by shreyasbharath** [comment]
Same here, how can we help to fix this?

**Comment by kbravh** [comment]
I have a fix that I'll be able to publish in about two hours, I've been stuck in an airport all day but I'll be back at my computer this evening.

**Comment by kbravh** [comment]
I've just published version 1.1.3 which resolves this issue. Because I had to remove the filename sanitization package I was using, there's a potential error when trying to save a file with a name that is too long, so I'm working to rewrite that piece in a way that's compatible with Obsidian.

**Comment by fuhadabdulla** [comment]
Thank you so much Kbravh
