### ISSUE TITLE
[feature request]. Option for "minimal version" - only author: [threaditemnumber] tweettext

### ISSUE THREAD

**Issue by tracure1337** [kbravh/obsidian-tweet-to-markdown#7]
[feature request]. Option for "minimal version" - only author: [threaditemnumber] tweettext

Thank you for this amazing plugin. 

Is there a way so I can just save the plain tweet text and the author name?  
And if it's a thread just number the items?

Maybe even an option to ONLY save the tweets of a thread and just number them or maybe even leave the numbering out too because many threads are manually numbered by authors already.

I don't need the images and links embedded in 99% of the target tweets in my case.

Thank you so much for consideration.

**Comment by kbravh** [comment]
That's a great suggestion! I'll get to work on implementing this.

**Comment by kbravh** [comment]
I've just pushed out version 2.1.0; you should see it soon. I've provided some extra options to slim down the tweet output. For example, to obtain the the output you're expecting, you can set the following options:

- [ ] Include profile pictures
- [x] Text only
- [ ] Include date

![image](https://user-images.githubusercontent.com/30562119/155359899-58f0bde4-0172-486f-8ce8-384627b3d55e.png)


Hope that helps!

**Comment by tracure1337** [comment]
wow!   @kbravh   Thanks sooo much!

**Comment by tracure1337** [comment]
@kbravh  works like a charm.  Maybe can we have one small option to either add the link or not.

I only now realized I'd like to keep the link to the tweet so I can properly cite the authors :-)

**Comment by kbravh** [comment]
Good point, I'll probably just split the minimal option into separate "Include images" and "Include links" options.

**Comment by kbravh** [comment]
I've just pushed up version 2.3.1. Instead of the `textOnly` option, there are now two new options: `includeImages` and `includeLinks`. Disabling both of those acts the same as `textOnly`. But now you can leave images out while still including links for citation purposes. Hope this helps!

**Comment by tracure1337** [comment]
@kbravh 

I added a diff image how is right now and how I'd like to be able to process the tweets.

And then if it could pull all of them from my twitter bookmarks (and then nuke them)  I'd be soo happy :-)

This is how the original looks:
![CleanShot 2022-04-15 at 23 02 17@2x](https://user-images.githubusercontent.com/43231640/163631611-5ba28581-131f-49a3-8891-458dac088573.jpg)




I manually edit them to look like this:

![CleanShot 2022-04-15 at 23 00 40@2x](https://user-images.githubusercontent.com/43231640/163631529-ed2f63c6-6ba1-4634-b4e7-5cd7d0326cbf.jpg)



EDIT: Forgot to remove a date at 3.

**Comment by kbravh** [comment]
Oh okay, this makes much more sense. Sorry I didn't get it 😅 Let me see what I can do!

Also, Twitter _just_ released an API endpoint for working with bookmarks. I'll look into it!

**Comment by tracure1337** [comment]
@kbravh  Thanks. No problem at all, my explanation was lacking as well 😺 

Can't wait to see what you can come up with 👍

**Comment by kbravh** [comment]
@cocoonkid I've just released a new **Condensed thread** option in version 2.5.0. Please give it a go and let me know what you think! I believe this is much more of what you were looking for. The left file is a regular thread, and the right file is a condensed thread.
![condensed_thread](https://user-images.githubusercontent.com/30562119/163689215-7492dd41-e8ae-40a6-836b-ec2e929f4163.png)

**Comment by tracure1337** [comment]
@kbravh THANKS SO MUCH SIR!
