### ISSUE TITLE
[bug].  Special chars are converted to HTML entities.

### ISSUE THREAD

**Issue by tracure1337** [kbravh/obsidian-tweet-to-markdown#8]
[bug].  Special chars are converted to HTML entities.

For example & became  `&amp;`

**Comment by kbravh** [comment]
Interesting, I wonder if this is a side effect of using the built-in Obsidian request module. Let me try using a different library to make the requests. Good catch!

**Comment by kbravh** [comment]
I've fixed this in version 2.0.3 that was just released. Thanks again for catching it.
