### ISSUE TITLE
"Date of tweet" is always the current date/time

### ISSUE THREAD

**Issue by gapmiss** [kbravh/obsidian-tweet-to-markdown#9]
When "include date" setting is ON, the date next to each tweet is always the current date/time. I was expecting the tweet's create time to be displayed for each individual tweet. Is this the expected behavior? Thank you

**Comment by kbravh** [comment]
This is not expected behavior 🤔 Let me investigate.

**Comment by gapmiss** [comment]
Example screenshot saved just now
![CleanShot – Obsidian - pkm - Obsidian v0 13 23 – 2022-02-26 at 11 19 10](https://user-images.githubusercontent.com/98914514/155850631-59a49c89-0307-4963-8174-af74d08f7955.png)

**Comment by kbravh** [comment]
Alright, I've found the bug and patched it! 

The TTM server wasn't requesting the created_at field from Twitter, and Obsidian just defaulted to the current date. The fix should be live now, so I'll close this. Let me know if you run into any further issues.

**Comment by gapmiss** [comment]
Thank you for the quick server side fix.

Regarding the "200" tweet monthly limit, is that a hard limit? Does the plugin fail when the limit is reached? If one gets a Twitter bearer token, does that 200 limit apply? I am assuming that with the bearer token, the limit is then 50K tweets and the limit is 200 for your SAAS at https://ttm.kbravh.dev ?

**Comment by gapmiss** [comment]
FWIW, if you would lift the limit for my "gapmiss" account, I could do some more intensive testing.

Should this thread be recognized as a "thread?"
https://twitter.com/Mensthetics/status/1476552798594605056

When testing, I only get the single tweet.

**Comment by kbravh** [comment]
> Thank you for the quick server side fix.
> 
> Regarding the "200" tweet monthly limit, is that a hard limit? Does the plugin fail when the limit is reached? If one gets a Twitter bearer token, does that 200 limit apply? I am assuming that with the bearer token, the limit is then 50K tweets and the limit is 200 for your SAAS at https://ttm.kbravh.dev ?

The limit is a hard limit; you'll just get back an error letting you know that the limit was reached. The limit only applies to https://ttm.kbravh.dev; if you go through the Twitter application and get your own bearer token, you will have 50k tweet per month (and up to 2 million if you request elevated permission). 

> Should this thread be recognized as a "thread?" https://twitter.com/Mensthetics/status/1476552798594605056

I've just tested this myself and the entire thread came through without issue. Please make sure to switch the thread toggle button so that the plugin knows to work back up the thread. 
![image](https://user-images.githubusercontent.com/30562119/155857463-6727c423-0829-4cb1-9db4-86f7cd941221.png)

If you notice any problems, please do open up another issue on the repository.

**Comment by gapmiss** [comment]
Very strange, but I've "lost" that setting. I do remember checking that box when I 1st installed the plugin. Now it is not in the settings. I can open a new issue if need be.

![CleanShot – Obsidian - pkm - Obsidian v0 13 23 – 2022-02-26 at 17 45 11](https://user-images.githubusercontent.com/98914514/155861446-4bebb61d-6b99-4a09-aa9f-b85d2a72db83.png)

**Comment by kbravh** [comment]
Sorry for not clarifying; that option only appears on the popup when you click the tweet icon on the sidebar. There's currently not a way to download a thread just by pasting a tweet link, though I am working on it.
![image](https://user-images.githubusercontent.com/30562119/155862811-a634a90c-d5ed-4a62-8f2d-a54323b79c48.png)

**Comment by gapmiss** [comment]
Ah, yes, I had got to that screen previously thru `⌘ + P`. Thank you for helping me remember.

# 1st-class plugin!
